server:
  port: 8083

spring:
  application:
    name: auth-service

aws:
  cognito:
    region: eu-west-1
    userPoolId: ${AWS_COGNITO_USER_POOL_ID}
    clientId: ${AWS_COGNITO_CLIENT_ID}
    clientSecret: ${AWS_COGNITO_CLIENT_SECRET}
    jwk: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json