server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=3
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - StripPrefix=3
        - id: invitation-service
          uri: lb://invitation-service
          predicates:
            - Path=/api/v1/invitations/**
          filters:
            - StripPrefix=3

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

aws:
  cognito:
    region: ${AWS_REGION:us-east-1}
    userPoolId: ${AWS_COGNITO_USER_POOL_ID:your-user-pool-id}
    jwk-set-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json

jwt:
  secret: ${JWT_SECRET:veryLongAndSecureSecretKeyThatShouldBeStoredInConfigServerInProduction}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always