server:
  port: 8082

spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/organization_service_db
    username: ${ORGANIZATION_SERVICE_DB_USER}
    password: ${ORGANIZATION_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/