server:
  port: 8085

spring:
  application:
    name: invitation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/invitation_service_db
    username: ${INVITATION_SERVICE_DB_USER}
    password: ${INVITATION_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always